#!/usr/bin/env bash

# sh template: preliminary part {{{
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `

vim_opts="-n -p"
v="vim $vim_opts"

define_base_dirs(){
# {{{
# main Wales group software directory
export wg_dir="$shd/../../"
packdir=$HOME/arch/packed
unpackdir=$HOME/arch/unpacked
# }}}
}


set_base_vars(){
# {{{
s_purpose="script for working with BibTeX files"
s_project="~/scripts"
# }}}
}

set_base_vars

display_help(){
# general part {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: $s_project
PURPOSE: $s_purpose
USAGE: $this_script [ OPTIONS ] [ BIBTEX FILE(S) ]

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	
EOF
# }}}
# script-specific {{{
cat << EOF
	============

	rm *		remove:
				k 	 	keywords 

	v		view:
				abs 	 	abstract 
				
	l		list:

REMARKS:
USAGE EXAMPLES:
	$this_script rm k repdoc.bib 
			remove all keywords from repdoc.bib

AUTHOR: O. Poplavskyy
=============================================
EOF
# }}}
}
# }}}
[ -z "$*" ] && ( display_help; exit 0 )

main(){
# {{{

case "$1" in
  "")
  ;;
  *)
  ;;
esac    # --- end of case ---

# }}}
}

# main part 
# {{{

script_opts=( $* )
define_base_dirs

while [ ! -z "$1" ]; do
  	case "$1" in
		  #{{{
	  	vm) $v $0; exit ;;
		h) display_help $*; exit ;;
	  	*) main $* && exit 0 ;;
	esac
  	shift
        #}}}
done

# }}}
