#!/usr/bin/env bash

# sbvars() dhelp() {{{

sbvars(){
#{{{
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `
# shell file with functions
export fsh="$hm/scripts/f.sh"
export bfile=`mktex.pl --var bibfile `.bib

vim_opts="-n -p"
v="vim $vim_opts"

# }}}
}

sbvars
source $fsh

dhelp(){
# general part {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: 
	~/scripts/
PURPOSE: 
	script for working with BibTeX files
USAGE: $this_script [ OPTIONS ] [ BIBTEX FILE(S) ]

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	
EOF
# }}}
# script-specific {{{
cat << EOF
	============

	--------------------------
	List ...
	--------------------------

	lk		list paper keys
	lkkw	list paper keys for the given keyword
	la		list authors
	lak		list authors, number of keys and the list of keys 

	--------------------------
	pk* - Given the key, print:
	--------------------------

	pkt		print entry title given its key

	--------------------------
	File operations 
	--------------------------

	rw		re-write the bibfile

REMARKS:
DEFAULTS:
	bib-file:
		$bfile
USAGE EXAMPLES:
	$this_script lk S
		List all paper keys which name begins with S, e.g,
		$this_script lk A lists all keys starting with 'A'
	$this_script la AUTH
		List all authors whose name begins with AUTH, e.g.
		$this_script la A  gives all authors whose name begins with 'A'
	$this_script lak AUTH 
		List authors beginning with AUTHOR - number of entries - entries
		e.g. $this_script lak W lists all authors whose name begins with 'W'

AUTHOR: O. Poplavskyy
=============================================
EOF
# }}}
}

[ -z "$*" ] && ( dhelp; exit 0 )

# }}}

main(){
# {{{

case "$1" in
  "")
  ;;
  verr) bt.pl --infile $bfile --list pkeys  >& n; cat n | awk '/error/' >& $bfile.err; v err ;;
  vwarn) bt.pl --list pkeys --infile $bfile >& n; cat n | awk '/warning/' >& $bfile.warn; v warn ;;
  lk)  #list keys {{{
  		opt="pkeys"
  		ofile="bib.$opt.i.dat"
  		bt.pl --list $opt --infile $bfile --startstring $2 > n 2>/dev/null; 
  		cat n | sed '/warning:/d; /error:/d' | sort > $ofile ; 
  		cat $ofile   
		;;
	  #}}}
  la)  #list authors {{{
  		ofile="bib.auth.i.dat"
  		bt.pl --list authors --infile $bfile --startstring $2 > n 2>/dev/null; 
  		cat n | sed '/warning:/d; /error:/d ' > $ofile ; 
  		cat $ofile   
		;;
	  #}}}
  lak)  #list authors and their keys{{{
  		opt="auth_pkeys"
  		ofile="bib.$opt.i.dat"
  		bt.pl --list $opt --infile $bfile --startstring $2 > n 2>/dev/null ; 
  		cat n | sed '/warning:/d; /error:/d ' > $ofile ; 
  		cat $ofile   
		;;
	  #}}}

  esac    # --- end of case ---

# }}}
}

# main part 
# {{{

script_opts=( $* )

while [ ! -z "$1" ]; do
  	case "$1" in
		  #{{{
	  	vm) $v $0 $fsh $shd/$this_script.pl; exit ;;
		h) dhelp $*; exit ;;
	  	*) main $* && exit 0 ;;
	esac
  	shift
        #}}}
done

# }}}
