#!/bin/bash
 
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `
# main Wales group software directory
export wg_dir="$shd/../../"

vim_opts="-n -p"
v="vim $vim_opts"

display_help(){
# {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PURPOSE: Converter script
USAGE: $this_script [ OPTIONS ] 

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	
	============

REMARKS:
AUTHOR: O. Poplavskyy
=============================================
EOF
# }}}
}

[ -z $* ] && ( display_help; exit 0 )

# main part 
# {{{

script_opts=( $* )

while [ ! -z "$1" ]; do
  	arg="$1"
  	shift
  	case "$arg" in
		  #{{{
	  	vm) $v $0; exit ;;
		h) display_help $*; exit ;;
		) pats=( "BEGIN:VCARD" "END:VCARD" \
			"EMAIL;TYPE=OTHER:" \
			"NICKNAME:" \
			"NOTE:" \ 
			"FN:" \ 
			"N:" )
	  	*) ;;
	esac
        #}}}
done

# }}}

