#!/bin/bash

this_script=` basename $0 `
export shd="`dirname $(readlink -f $0)`"
vrt=$HOME/vrt/

vim_opts="-n -p"
v="vim $vim_opts"
let i=0

set_files(){
#{{{
for f in "${bf[@]}"; do
	files[$i]=$od$f
	i=$(($i+1))
done
#}}}
}

if [ -z "$1" ]; then 
cat << EOF
================================================
SCRIPT NAME: $this_script
USAGE: $this_script OPTS
PURPOSE: 
	configuration of different things; 
	running ./configure scripts
OPTS:
		display help message

	m,vm	view myself

	rg	ranger
	s	screen
	pn	~/.pinerc
	v	edit ~/.vimrc
	b	edit ~/.bashrc

	lasu	Latex-Suite files 

	h	./configure --prefix=\$HOME \$*
	hi	cnf h && make && make install
================================================
EOF
else
  while [ ! -z "$1" ]; do
		case $1 in
		  	lasu) 
				od=$vrt/ftplugin/latex-suite/
				bf=( main.vim envmacros.vim elementmacros.vim bibtex.vim opmacros.vim \
			        	custommacros.vim texrc ../tex_latexSuite.vim )
			;;
        		"rg") od=$hm/.config/ranger/ ; bf=( "*.py" "scope.sh" ) ;;
			"s") bf=( .screenrc ) ; od=~/ ;; 
			"b") bf=( .bashrc ) ; od=~/ ;; 
			"v") bf=( .vimrc ) ; od=~/ ;; 
			"pn") bf=( .pinerc ) ; od=~/ ;; 
			"m" | "vm") bf=( $0 ) ; od="" ;;
			"h") shift ; ./configure --prefix=$HOME $* ; exit ;;
			"for") bf=( $vrt/ftplugin/fortran.vim $vrt/syntax/fortran.vim $vrt/plugin/SyntaxFolds.vim $HOME/.vimrc ) od="" ;;
		esac
		set_files
		shift
	done
	$v $files
fi
