#!/usr/bin/env bash

# sh template: preliminary part {{{
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `

vim_opts="-n -p"
v="vim $vim_opts"

define_base_dirs(){
# {{{
# main Wales group software directory
export wg_dir="$shd/../../"
packdir=$HOME/arch/packed
unpackdir=$HOME/arch/unpacked
# }}}
}


set_base_vars(){
# {{{
s_purpose="view source files with vim"
s_project="Wales group svn repository"
s_project="~/scripts"
# }}}
}

set_base_vars

display_help(){
# general  {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: ~/wrk/rep
PURPOSE: convert images between different formats
USAGE: $this_script STRING

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	
	============
EOF
# }}}
# script-specific part {{{
cat << EOF

	rq Q		convert images in the current directory into new ones 
				with reduced quality Q (in range 1-100). 
				Output images are stored in the directory called lowQ/

REMARKS:
AUTHOR: O. Poplavskyy
=============================================
EOF
# }}}
}
# }}}
[ -z "$*" ] && ( display_help; exit 0 )

exts=( gif ps pdf png bmp jpg )
#picdir=$PWD/pics/
picdir=$PWD
#picdir=$hm/reptex/pics
#picdir=$hm/wrk/rep/ppics


main(){
# {{{

case "$1" in
  rq)
	  Q=$2
	  dir=Q$Q
	  mkdir -p $dir
	  find . -maxdepth 1 -iname '*jpg' -exec convert -quality $Q {} $dir/{} \; 
  ;;
  *)    cd $picdir/$1
        #files=( ` ls *.png *.gif *.jpg *.bmp | awk "/^$1/"` )
  	files=( ` ls *.png *.gif *.jpg *.bmp ` )
	for file in ${files[@]}; do
  		fname=${file%.*}
  		fext=${file##*.}
		convert $file $fname.eps
	done
	cd -
  ;;
esac    # --- end of case ---

# }}}
}

# main part 
# {{{

script_opts=( $* )
define_base_dirs

while [ ! -z "$1" ]; do
  	case "$1" in
		  #{{{
	  	vm) $v $0; exit ;;
		h) display_help $*; exit ;;
	  	*) main $* && exit 0 ;;
	esac
  	shift
        #}}}
done

# }}}




