#!/usr/bin/env bash

# sbvars() dhelp() {{{

sbvars(){
# {{{
s_purpose=" ... convert PDF papers to DJVU format and copy to:"
s_project=" ~/scripts"

# name of this script 
export this_script=` basename $0 `
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# shell functions file
export fsh="$hm/scripts/f.sh"

export papdir=$hm/doc/papers/ChemPhys/
export ddir=$hm/wrk/p/djvu

vim_opts="-n -p"
v="vim $vim_opts"
gitdirs=( "config" "scripts" "templates" "vrt" "install" "coms" "cit" )

# }}}
}

sbvars
source $fsh

dhelp(){
# {{{
# general beginning part {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: $s_project
PURPOSE: 
	Convert a PDF paper in directory: 
		$papdir	
	to DJVU format and copy the final DJVU file to:
		$ddir
USAGE: $this_script [ OPTIONS ] 

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	-g		gvim invocation
	
	============
EOF
# }}}
# actual interesting part {{{
cat << EOF

	FILE	- filename for the paper in the PDF format. e.g.
		$this_script FILE takes FILE.pdf as input and then
		produces FILE.djvu as output

EOF
# }}}
# final general part {{{
cat << EOF
REMARKS:
AUTHOR: O. Poplavskyy
SCRIPT LOCATION:
	$0
=============================================
EOF
# }}}
# }}}
}

[ -z "$*" ] && ( dhelp; exit 0 )

#}}}

main(){

# intro messages {{{

e_delim 100 "="
eoos "Input (PDF) papers directory: $papdir" 
eoos "Output (DJVU) directory: $ddir" 

#}}}
# while-loop  {{{

while [ ! -z "$1" ]; do 
	case "$1" in
	  "") ;;
	  -s) # short paper key {{{
	  	eoos "-s: short paper key option"	
	  	export pkey=`lpk $2 ` ; 
		 	eoos "Short paper key provided: $2"  
		if [ ! -z $pkey ]; then 
		 	eoos "Long paper key is: $pkey"  
		  else
		 	eoor "Couldn't convert to the long form: $2"  
		  fi
	  shift ;;
		# }}}
	  *) pkey=$1  
		 	eoos "Long paper key is: $pkey"  
			;;
	esac    
	shift
done

#}}}
# dealing with files {{{

if [ ! -z $pkey ]; then  
	files=( ` find $papdir -name $pkey\*.pdf ` )
		  for p in ${files[@]}; do
				eoos "	Converting file: "
				eoos "		$p"
				pbare=$( basename $p )
				dp=${pbare%.pdf}.djvu
				e_delim 50 "-"
		  		pdf2djvu $p -o $ddir/$dp
				e_delim 50 "-"
		  done
fi
#}}}

}

# main part 
# {{{

script_opts=( $* )

# read cmd args => main()  {{{
while [ ! -z "$1" ]; do
  	case "$1" in
		  #{{{
	  	vm) $v $0 $fsh; exit ;;
		h) dhelp $*; exit ;;
		-g) v="$v -g" ;;
	  	*) main $* && exit 0 ;;
	esac
  	shift
        #}}}
done

# }}}
