#!/usr/bin/env bash

# sbvars set_base_dirs dhelp {{{

sbvars(){
# {{{
s_purpose="copy from remote machine to local"
s_project="~/scripts"

# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `
# vim
vim_opts="-n -p"
v="vim $vim_opts"
# ssh 
export locport=10000

# }}}
}

sbvars

dhelp(){
# {{{
# general beginning part {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: $s_project
PURPOSE: $s_purpose
USAGE: $this_script [ OPTIONS ] 

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	-g		gvim invocation
	
	============
EOF
# }}}
# actual interesting part {{{
cat << EOF

some option

EOF
# }}}
# final general part {{{
cat << EOF
REMARKS:
AUTHOR: O. Poplavskyy
SCRIPT LOCATION:
	$0
=============================================
EOF
# }}}
# }}}
}

[ -z "$*" ] && ( dhelp; exit 0 )

#}}}

main(){
# {{{

username="op226"
homedir=/home/$username
mach="$username"@localhost

# read cmd args {{{
while [ ! -z "$1" ]
    do
        case "$1" in
            "-hp")   export hostport="$2" ;;
            "-lp")   export locport="$2" ;;
  			"-from") from=$mach:$homedir/$2 ;;
 			"-to") to=$2 ;; 
		esac
		shift
done

rsync -ave "ssh -p $locport -oNoHostAuthenticationForLocalhost=yes" $from $to
# }}}
}

# main part 
# {{{

script_opts=( $* )

while [ ! -z "$1" ]; do
  	case "$1" in
		  #{{{
	  	vm) $v $0 $hm/scripts/f.sh; exit ;;
		h) dhelp $*; exit ;;
		-g) v="$v -g" ;;
	  	*) main $* && exit 0 ;;
	esac
  	shift
        #}}}
done

# }}}
