#!/usr/bin/env bash
 
#{{{
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `

vim_opts="-n -p"
v="vim $vim_opts"
repos=( "config" "scripts" "templates" "vrt" "install" "doc-coms" "doc-cit" )


sbdirs(){
# {{{
# main Wales group software directory
export wg_dir="$shd/../../"
packdir=$HOME/arch/packed
unpackdir=$HOME/arch/unpacked
# }}}
}


dhelp(){
# {{{
# general beginning part {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: $s_project
PURPOSE: $s_purpose
USAGE: $this_script [ OPTIONS ] 

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	-g		gvim invocation
	
	============
EOF
# }}}
# actual interesting part {{{
cat << EOF

some option

EOF
# }}}
# final general part {{{
cat << EOF
REMARKS:
AUTHOR: O. Poplavskyy
=============================================
EOF
# }}}
# }}}
}

[ -z "$*" ] && ( dhelp; exit 0 )

sbvars(){
# {{{
s_purpose="copy data files from the cluster"
s_project="~/scripts"

#datadir=$hm/data/2011/10-09-11
datadir=$hm/data/2011/12-09-11
datadir=$hm/data/2011/
server="$mq"
suff="mek"
remote="$server:~/gops/pbs/s/*$suff* "
local="$datadir"
# }}}
}
#}}}

sbvars

main(){
# {{{ 

cd $datadir

case "$1" in
  a) 
  rsync -avz --size-only $remote $local   
  ;;
  *) ;;
esac    # --- end of case ---

# }}}
}

# main part 
# {{{

script_opts=( $* )
sbdirs

while [ ! -z "$1" ]; do
  	case "$1" in
		  #{{{
	  	vm) $v $0; exit ;;
		h) dhelp $*; exit ;;
		-g) v="$v -g" ;;
	  	*) main $* && exit 0 ;;
	esac
  	shift
        #}}}
done

# }}}
