#!/bin/bash

this_script=` basename $0 `
vim_opts="-n -p"
v="vim $vim_opts"

#docdir="$HOME/doc/coms"
docdir="$HOME/doc-coms"
citdir="$HOME/doc-cit"
d="$docdir"
cd $d ; 
entries=( ` ls *.tex  |  sed 's/.tex$//g' ` ); 
cd -

if [ -z "$1" ]; then 
#display help message {{{
cat << EOF
================================================
SCRIPT NAME: $this_script
USAGE: $this_script OPTS
PURPOSE: display documentation for different things
OPTS:
	${entries[@]}
PARAMETERS:
	docs directory:		$docdir
================================================
EOF
#}}}
else
  #{{{
  	case $1 in
	  	vm) $v $0 ;; 
		cit) 	
			cd $citdir; 
			citfiles=( ` find . -name "*.bib" ` ) 
			$v ${citfiles[@]}
			;;
		*)
		  	case "$1" in
			  g | gmin) file=gmin ;; 
			  o | optim) file=optim ;; 
			  ls)
			  	 start=$2 
			 	 cd $d ; 
				 entries=( ` ls *.tex | awk "/^$start/" |  sed 's/.tex$//g' ` ); 
				 echo "${entries[@]}"	
			   	 exit 
				 ;;
			  ps | pathsample) file=pathsample ;; 
			  *) file=$1 ;; 
			esac
			
			$v $d/$file.tex
		;;
      esac
#}}}
fi
