#!/bin/bash

this_script=` basename $0 `
vim_opts="-n -p"
v="vim $vim_opts"

docdir="$HOME/doc/coms"
d="$docdir"

if [ -z "$1" ]; then 
cat << EOF
================================================
SCRIPT NAME: $this_script
USAGE: $this_script OPTS
PURPOSE: display documentation for different things
OPTS:
	awk sed rsync pbs 
PARAMETERS:
	docs directory:		$docdir
================================================
EOF
else
  	case $1 in
	  	vm) $v $0 ;; 
		*)
		  	case "$1" in
			  g | gmin) file=gmin ;; 
			  o | optim) file=optim ;; 
			  ls) cd $d ; ls $d ;;
			  ps | pathsample) file=pathsample ;; 
			  *) file=$1 ;; 
			esac
			
			$v $d/$file.tex
		;;
      esac
fi
