#!/usr/bin/env bash
 
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `

vim_opts="-n -p"
v="vim $vim_opts"

define_base_dirs(){
# {{{
# main Wales group software directory
export wg_dir="$shd/../../"
packdir=$HOME/arch/packed
unpackdir=$HOME/arch/unpacked
# }}}
}


set_base_vars(){
# {{{
s_purpose="shortcut for git pull"
s_project="~/scripts"
# }}}
}

set_base_vars

display_help(){
# {{{
# general beginning part {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: $s_project
PURPOSE: $s_purpose
USAGE: $this_script [ OPTIONS ] 

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	
	============

	vn		
	-s source
	-p prog
	-o opts
EOF
# }}}
# actual interesting part {{{
cat << EOF

some option

EOF
# }}}
# final general part {{{
cat << EOF
REMARKS:
AUTHOR: O. Poplavskyy
=============================================
EOF
# }}}
# }}}
}

[ -z "$*" ] && ( display_help; exit 0 )

main(){
# {{{

prog=`pwd | awk -F "/" '{ print $NF }'`
src=""
com="pull"
dirs=( `pwd` ) 


while [ ! -z "$1" ]; do
	case "$1" in
		vn) src="0502790@venus.phys.uu.nl" ;;
		-s) src="$2" ;; 
		-p) prog="$2" ;; 
		-o) opts="$2" ;;
		0 | pull)  com="pull" ;;
		1 | push)  com="push" ;;
		a) dirs=( config scripts templates gops wchf  ) ;;
	esac    
	shift
done

git_source="ssh://$src/home/students/0502790/git/$prog.git" 
#git_source=""

for dir in ${dirs[@]}; do
	echo "Pulling $dir..."
	echo "git command: $com"
  	if [ -d $dir ]; then 
	  	cd $HOME/$dir
		git $com $git_source $opts
        fi
done
# }}}
}

# main part 
# {{{

script_opts=( $* )
define_base_dirs

while [ ! -z "$1" ]; do
  	case "$1" in
		  #{{{
	  	vm) $v $0; exit ;;
		h) display_help $*; exit ;;
	  	*) main $* && exit 0 ;;
	esac
  	shift
        #}}}
done

# }}}


