#!/bin/bash
 
# sbvars() dhelp() {{{

sbvars(){
  #{{{
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `

vim_opts="-n -p"
v="vim $vim_opts"
venus="0502790@venus.phys.uu.nl"
repos=( "config" "scripts" "templates" "vrt" "install" "doc-coms" "doc-cit" ) 
export ext=.tar.gz
packdir=$HOME/arch/packed
unpackdir=$HOME/arch/unpacked
#}}}
}

sbvars

cdpack(){
cd $packdir
}

dhelp(){
# {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: ~/scripts/
PURPOSE: 
USAGE: $this_script [ OPTIONS ] 

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	
	============

	vim	

REMARKS:
AUTHOR: O. Poplavskyy
=============================================
EOF
# }}}
}
#}}}

[ -z $* ] && ( dhelp; exit 0 )

# main part 
# {{{

script_opts=( $* )

mkdir -p $packdir $unpackdir

while [ ! -z "$1" ]; do
  	arg="$1"
  	shift
  	case "$arg" in
		  #{{{
	  	vm) $v $0; exit ;;
		h) dhelp $*; exit ;;
		vim) cd $unpackdir/$1 ; ./i ;; 
		#*) atool $packdir/$1$ext -X $unpackdir/  ;;
		-r) ;;
		cpan) 
			mods=( `cat $shd/perl/ins.cpan.i.dat | sed '/^\s*#/d' ` )
			for m in ${mods[@]}; do 
				perl -MCPAN -e "install $m" 
		 	done 
			exit 
		;;
		xvn) # install ssh to venus access {{{
		ssh-keygen -t rsa 
		pubkey=~/.ssh/id_rsa.pub
		hmserv=/home/students/0502790/
		akeys=$hmserv/.ssh/authorized_keys
		#scp .ssh/id_rsa.pub $venus:~/.ssh/$pubkey.$HOSTNAME
		cat $pubkey | ssh $venus cat ">>" $akeys
		;;
		# }}}
		a)  # all first-importance repos {{{
			for repo in ${repos[@]}; do 
			  	if [ ! -d $HOME/$repo ]; then 
				  	cd $HOME
					git clone $venus:~/git/$repo.git/
			      	else
				  	cd $HOME/$repo
					git pull $venus:~/git/$repo.git/ master
				fi
		      	done 
		;;
		# }}}
	esac
        #}}}
done

# }}}
