#!/bin/bash
 
#{{{
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `

vim_opts="-n -p"
v="vim $vim_opts"
venus="0502790@venus.phys.uu.nl"
repos=( "config" "scripts" "templates" "vrt" "install" "doc-coms" "doc-cit" ) 

define_base_dirs(){
# main Wales group software directory

export wg_dir="$shd/../../"
packdir=$HOME/arch/packed
unpackdir=$HOME/arch/unpacked

}

define_base_vars(){
ext=.tar.gz
}

cdpack(){
cd $packdir
}

display_help(){
# {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: ~/scripts/
PURPOSE: 
USAGE: $this_script [ OPTIONS ] 

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	
	============

	vim	

REMARKS:
AUTHOR: O. Poplavskyy
=============================================
EOF
# }}}
}
#}}}

[ -z $* ] && ( display_help; exit 0 )

# main part 
# {{{

script_opts=( $* )

mkdir -p $packdir $unpackdir

while [ ! -z "$1" ]; do
  	arg="$1"
  	shift
  	case "$arg" in
		  #{{{
	  	vm) $v $0; exit ;;
		h) display_help $*; exit ;;
		vim) cd $unpackdir/$1 ; ./i ;; 
		#*) atool $packdir/$1$ext -X $unpackdir/  ;;
		-r) ;;
		xvn) # install ssh to venus access {{{
		ssh-keygen -t rsa 
		pubkey=~/.ssh/id_rsa.pub
		hmserv=/home/students/0502790/
		akeys=$hmserv/.ssh/authorized_keys
		#scp .ssh/id_rsa.pub $venus:~/.ssh/$pubkey.$HOSTNAME
		cat $pubkey | ssh $venus cat ">>" $akeys
		;;
		# }}}
		a)  # all first-importance repos {{{
			for repo in ${repos[@]}; do 
			  	if [ ! -d $HOME/$repo ]; then 
				  	cd $HOME
					git clone $venus:~/git/$repo.git/
			      	else
				  	cd $HOME/$repo
					git pull $venus:~/git/$repo.git/ master
				fi
		      	done 
		;;
		# }}}
	esac
        #}}}
done

# }}}
