#!/usr/bin/env bash

# sbvars() dhelp() {{{

sbvars(){
# {{{
s_purpose=" ... script purpose ..."
s_project=" ~/scripts"

# name of this script 
export this_script=` basename $0 `
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"

vim_opts="-n -p"
v="vim $vim_opts"
repos=( "config" "scripts" "templates" "vrt" "install" "doc-coms" "doc-cit" )

export jmldir="$hm/scripts/JML"
jmlfiles=( ` find $jmldir -name \*.spt -o -name \*.jmol ` )
export jmolexe="$hm/arch/unpacked/jmol/jmol.sh"
export jmols="$jmldir/m.jmol"
export exec=0

# }}}
}

sbvars

dhelp(){
# {{{
# general beginning part {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: $s_project
PURPOSE: $s_purpose
USAGE: $this_script [ OPTIONS ] 

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	-g		gvim invocation
	
	============
EOF
# }}}
# actual interesting part {{{
cat << EOF

some option

EOF
# }}}
# final general part {{{
cat << EOF
REMARKS:
AUTHOR: O. Poplavskyy
SCRIPT LOCATION:
	$0
=============================================
EOF
# }}}
# }}}
}

[ -z "$*" ] && ( dhelp; exit 0 )

#}}}

main(){
# read cmd args {{{

while [ ! -z "$1" ]; do 
	case "$1" in
	  v) ;;
	  i) # produce images {{{
	  export image=1 
cat << eof
var filename = "$pic"
write IMAGE 800 600 $pic_ext @filename
eof
;;
#}}}
	-if) #  specify an input file {{{
	  	iffile=$2; shift 
cat << eof
		load trajectory "$iffile"
eof
;;
#}}}
	  x|xgo) # execute for Go-model {{{ 
	  	export exec=1
	  	export jmols="$jmldir/$1.jmol"
cat >& $jmols << eof 
load trajectory $jmldir/xyz/1.le
script $jmldir/init.jmol
script $jmldir/goconnect.jmol
script $jmldir/blnseq.jmol
script $jmldir/fin.jmol
eof
  		;;
	  #}}}
	  # "e" stands for "echo" {{{
	  -e) s=$2 ; shift
		  case "$s" in
		  	goconnect) # {{{
cat << eof

color bonds white

select atomno=20, atomno=1; connect(selected); 
select atomno=24, atomno=1; connect(selected); 
select atomno=45, atomno=1; connect(selected); 
select atomno=24, atomno=2; connect(selected); 
select atomno=43, atomno=2; connect(selected); 
select atomno=45, atomno=2; connect(selected); 
select atomno=18, atomno=3; connect(selected); 
select atomno=20, atomno=3; connect(selected); 
select atomno=25, atomno=3; connect(selected); 
select atomno=26, atomno=3; connect(selected); 
select atomno=43, atomno=3; connect(selected); 
select atomno=26, atomno=4; connect(selected); 
select atomno=41, atomno=4; connect(selected); 
select atomno=16, atomno=5; connect(selected); 
select atomno=18, atomno=5; connect(selected); 
select atomno=26, atomno=5; connect(selected); 
select atomno=27, atomno=5; connect(selected); 
select atomno=28, atomno=5; connect(selected); 
select atomno=41, atomno=5; connect(selected); 
select atomno=28, atomno=6; connect(selected); 
select atomno=39, atomno=6; connect(selected); 
select atomno=16, atomno=7; connect(selected); 
select atomno=28, atomno=7; connect(selected); 
select atomno=29, atomno=7; connect(selected); 
select atomno=30, atomno=7; connect(selected); 
select atomno=39, atomno=7; connect(selected); 
select atomno=30, atomno=8; connect(selected); 
select atomno=37, atomno=8; connect(selected); 
select atomno=14, atomno=9; connect(selected); 
select atomno=30, atomno=9; connect(selected); 
select atomno=31, atomno=9; connect(selected); 
select atomno=32, atomno=9; connect(selected); 
select atomno=37, atomno=9; connect(selected); 
select atomno=30, atomno=14; connect(selected); 
select atomno=31, atomno=14; connect(selected); 
select atomno=28, atomno=16; connect(selected); 
select atomno=29, atomno=16; connect(selected); 
select atomno=26, atomno=18; connect(selected); 
select atomno=24, atomno=20; connect(selected); 
select atomno=25, atomno=20; connect(selected); 
select atomno=45, atomno=24; connect(selected); 
select atomno=41, atomno=26; connect(selected); 
select atomno=43, atomno=26; connect(selected); 
select atomno=39, atomno=28; connect(selected); 
select atomno=41, atomno=28; connect(selected); 
select atomno=39, atomno=30; connect(selected); 
select atomno=37, atomno=32; connect(selected); 
select atomno=1, atomno=20; connect(selected); 
select atomno=1, atomno=24; connect(selected); 
select atomno=1, atomno=45; connect(selected); 
select atomno=2, atomno=24; connect(selected); 
select atomno=2, atomno=43; connect(selected); 
select atomno=2, atomno=45; connect(selected); 
select atomno=3, atomno=18; connect(selected); 
select atomno=3, atomno=20; connect(selected); 
select atomno=3, atomno=25; connect(selected); 
select atomno=3, atomno=26; connect(selected); 
select atomno=3, atomno=43; connect(selected); 
select atomno=4, atomno=26; connect(selected); 
select atomno=4, atomno=41; connect(selected); 
select atomno=5, atomno=16; connect(selected); 
select atomno=5, atomno=18; connect(selected); 
select atomno=5, atomno=26; connect(selected); 
select atomno=5, atomno=27; connect(selected); 
select atomno=5, atomno=28; connect(selected); 
select atomno=5, atomno=41; connect(selected); 
select atomno=6, atomno=28; connect(selected); 
select atomno=6, atomno=39; connect(selected); 
select atomno=7, atomno=16; connect(selected); 
select atomno=7, atomno=28; connect(selected); 
select atomno=7, atomno=29; connect(selected); 
select atomno=7, atomno=30; connect(selected); 
select atomno=7, atomno=39; connect(selected); 
select atomno=8, atomno=30; connect(selected); 
select atomno=8, atomno=37; connect(selected); 
select atomno=9, atomno=14; connect(selected); 
select atomno=9, atomno=30; connect(selected); 
select atomno=9, atomno=31; connect(selected); 
select atomno=9, atomno=32; connect(selected); 
select atomno=9, atomno=37; connect(selected); 
select atomno=14, atomno=30; connect(selected); 
select atomno=14, atomno=31; connect(selected); 
select atomno=16, atomno=28; connect(selected); 
select atomno=16, atomno=29; connect(selected); 
select atomno=18, atomno=26; connect(selected); 
select atomno=20, atomno=24; connect(selected); 
select atomno=20, atomno=25; connect(selected); 
select atomno=24, atomno=45; connect(selected); 
select atomno=26, atomno=41; connect(selected); 
select atomno=26, atomno=43; connect(selected); 
select atomno=28, atomno=39; connect(selected); 
select atomno=28, atomno=41; connect(selected); 
select atomno=30, atomno=39; connect(selected); 
select atomno=32, atomno=37; connect(selected); 
select none;
color bonds none;
eof
			;;
		  #}}}
		  init) # {{{
cat << eof
width = 640; height = 480;
#set axes on; color axes white
#axes scale 2.0
#axes unitcell
rotate x 0 ; rotate y 0;  rotate z 0
zoom on;  zoom 100
background green;
select all; spacefill 200
#set perspectiveModel 10;
labels on;  color labels black
set fontSize 14
eof
;;	
#}}}
   blnseq)  # bln sequence {{{
# BLN sequence is B9-N3-(LB)4-N3-B9-N3-(LB)5-L  
cat << eof
var Bc="red" ; var Nc="blue" ; var Lc="yellow"

select { atomno>0 and atomno <10 } ; color @Bc; label "%i"
select { atomno>9 and atomno <13 } ; color @Nc; label "%i"

select atomno=13; color @Lc; label "%i"
select atomno=14; color @Bc; label "%i"
select atomno=15; color @Lc; label "%i"
select atomno=16; color @Bc; label "%i"
select atomno=17; color @Lc; label "%i"
select atomno=18; color @Bc; label "%i"
select atomno=19; color @Lc; label "%i"
select atomno=20; color @Bc; label "%i"

select { atomno>20 and atomno < 24 } ; color @Nc; label "%i"
select { atomno>23 and atomno < 33 } ; color @Bc; label "%i"
select { atomno>32 and atomno < 36 } ; color @Nc; label "%i"

select atomno=36; color @Lc; label "%i"
select atomno=37; color @Bc; label "%i"
select atomno=38; color @Lc; label "%i"
select atomno=39; color @Bc; label "%i"
select atomno=40; color @Lc; label "%i"
select atomno=41; color @Bc; label "%i"
select atomno=42; color @Lc; label "%i"
select atomno=43; color @Bc; label "%i"
select atomno=44; color @Lc; label "%i"
select atomno=45; color @Bc; label "%i"

select atomno=46; color @Lc; label "%i"

for (var an=1; an <=45; an=an+1)
		  ann=an+1
		  select atomno=an,atomno=ann; connect (selected)
end for

eof
;;
# }}}
fin) # final {{{
cat << eof
set echo top left; font echo 20 serif bolditalic ; color echo white
eof
		  ;;
		#}}}
		esac 
		exit 0
	  ;;
	  #}}}
	esac    
	shift
done

if [ $exec -eq 1 ]; then 
	  $jmolexe -s "$jmols" &
	  exit 
fi

# }}}
}

# main part 
# {{{

script_opts=( $* )

# read cmd args => main()  {{{
while [ ! -z "$1" ]; do
  	case "$1" in
		  #{{{
		  vm) $v $0 ` find $hm/scripts/JML -name \*.jmol -o -name \*.spt ` $hm/scripts/f.sh; exit ;;
		h) dhelp $*; exit ;;
		-g) v="$v -g" ;;
	  	*) main $* && exit 0 ;;
	esac
  	shift
        #}}}
done

# }}}


