#!/bin/bash

# sbvars {{{
sbvars(){

export outdir=$PWD
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `

# ps2pdf_opts dvips_opts vim_opts {{{

# ps2pdf options taken from http://www.cs.toronto.edu/~dross/latex/

vim_opts="-n -p"

export ps2pdf_opts="-dOptimize=true -dUseFlateCompression=true \
	       -dMaxSubsetPct=100 -dCompatibilityLevel=1.2 \
		-dSubsetFonts=true -dEmbedAllFonts=true \
		-dAutoFilterColorImages=false \
		-dAutoFilterGrayImages=false \
		-dColorImageFilter=/FlateEncode \
		-dGrayImageFilter=/FlateEncode \
		-dModoImageFilter=/FlateEncode "	

export dvips_opts="-Pamz -Pcmz"
export dvips_opts="-Ppdf"

export mode="full"
export exe="latex"
# }}}
}
#}}}
# dvitops dvitopdf {{{
dvitops(){

dvips $dvips_opts -o $1.ps $1.dvi

}

dvitopdf(){
		
dvips $dvips_opts -o  $1.ps $1.dvi
ps2pdf $ps2pdf_opts $1.ps $1.pdf

}
# }}}
dojob(){ # {{{

case "$1" in
  	"full") # main (full cycle) mode: {{{ 
		$exe $ifname  
		makeindex $ifname
		bibtex $ifname 
		$exe $ifname 
		$exe $ifname 
		dvitopdf $ifname 

		#latex $ifname && bibtex $ifname && latex $ifname && latex $ifname && dvitopdf $ifname 
	;;
	# }}}
	"gls") makeglossaries $ifname ;;
	"simple") # simple latex-to-pdf {{{
		latex $ifname
		dvitopdf $ifname
	;; # }}}
	"convert") # convert dvi to pdf {{{
		dvitopdf $ifname
	;; # }}}
esac

mkdir -p $outdir
if [ -f $ffile ]; then
  	cp $ffile $outdir/$outfile
	echo "$this_script> $ffile copied to: "
	echo "		$outdir"
fi

} # }}}

sbvars

if [ -z "$1" ]
 	then
# help message {{{
cat << EOF
=============================================================
SCRIPT NAME: ltm
USAGE: ltm [options] [  latex filename (without extension) ]
OPTIONS:
	---------------
	General
	---------------

	vm	view myself - edit this script with vim
	c	clean files in the current directory, namely:
	    		rm -f *.pdf *.ps *.dvi 	
			    	*.bbl *.aux *.bak .*swp  	
				*.blg *.log *.lof *~  		
				*.lot *.out *.toc 		
				*.backup *.pdf *.ps *.d *.dmp *.idx 

	-od,--outdir  DIR
		output directory for *.ps *.pdf files. 
		Default is the current directory
	-if,--infile FILE 
		Input file name (without *.tex extension)
	-of,--outfile FILE
		Output file name (without *.pdf extension)

	---------------
	Latex-specific (yet to be implemented)
	---------------

	-f 	full latex cycle (set by default)
	-s	single latex + pdf generation
	-c	convert dvi to pdf
	-g	run "makeglossaries" command only

USAGE EXAMPLES:
	ltm rep 
		( source file rep.tex, output rep.pdf )
SCRIPT LOCATION:
	$0
=============================================================
EOF
# }}}
	else 
	  # {{{
while [ ! -z "$1" ]
	do
	  case "$1" in
	    "vm") vim $vim_opts $0 ;;
	    "c") rm -f *.ps *.dvi *.bbl *.aux *.bak .*swp *.blg *.log *.lof *~ *.lot *.out *.toc *.backup *.d *.dmp *.idx ; exit 
		;;
	    "-f") export  mode="full" ;;
	    "-s") export  mode="simple" ;;
	    "-c") export  mode="convert" ;;
	    "-g") export  mode="gls" ;;
	    "-od"|"--outdir") export outdir=$2; shift ;;
		"-of"|"--outfile") export outfile="$2".pdf; shift ;;
		"-if"|"--infile") export ifname=$2; shift ;;
		"--exe") export exe=$2; shift ;;
	    *)	export ifname="$1" ;;
	  esac
	  shift
	  # }}}
done

# exec part {{{

export infile="$ifname".tex
export ffile="$ifname".pdf

if [ -f $infile ]; then 
		if [ -z $outfile ]; then
  			export outfile="$ifname".pdf
	  	fi
	    dojob $mode 
	else
		echo "No such file! Exiting..."
		exit 1
fi
#}}}

fi

