#!/bin/bash

# set_base_vars {{{
set_base_vars(){

export outdir=$PWD
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `

# ps2pdf_opts dvips_opts vim_opts {{{

# ps2pdf options taken from http://www.cs.toronto.edu/~dross/latex/

vim_opts="-n -p"

export ps2pdf_opts="-dOptimize=true -dUseFlateCompression=true \
	       -dMaxSubsetPct=100 -dCompatibilityLevel=1.2 \
		-dSubsetFonts=true -dEmbedAllFonts=true \
		-dAutoFilterColorImages=false \
		-dAutoFilterGrayImages=false \
		-dColorImageFilter=/FlateEncode \
		-dGrayImageFilter=/FlateEncode \
		-dModoImageFilter=/FlateEncode "	

export dvips_opts="-Pamz -Pcmz"
export dvips_opts="-Ppdf"

export mode="full"
# }}}
}
#}}}
# dvitops dvitopdf {{{
dvitops(){

dvips $dvips_opts -o $1.ps $1.dvi

}

dvitopdf(){
		
dvips $dvips_opts -o  $1.ps $1.dvi
ps2pdf $ps2pdf_opts $1.ps $1.pdf

}
# }}}
dojob(){ # {{{

case "$1" in
  	"full") # main (full cycle) mode: {{{ 
		latex $fname
		#makeglossaries $fname
		bibtex $fname
		latex $fname
		latex $fname
		dvitopdf $fname
	;;
	# }}}
	"gls") makeglossaries $fname ;;
	"simple") # simple latex-to-pdf {{{
		latex $fname
		dvitopdf $fname
	;; # }}}
	"convert") # convert dvi to pdf {{{
		dvitopdf $fname
	;; # }}}
esac

mkdir -p $outdir
if [ -f $ffile ]; then
  	cp $ffile $outdir
	echo "$this_script> $ffile copied to: "
	echo "		$outdir"
fi

} # }}}

set_base_vars

if [ -z "$1" ]
 	then
# help message {{{
cat << EOF
=============================================================
SCRIPT NAME: ltm
USAGE: ltm [options] [  latex filename (without extension) ]
OPTIONS:
	---------------
	General
	---------------

	vm	view myself - edit this script with vim
	c	clean files in the current directory, namely:
	    		rm -f *.pdf *.ps *.dvi 	
			    	*.bbl *.aux *.bak .*swp  	
				*.blg *.log *.lof *~  		
				*.lot *.out *.toc 		
				*.backup *.pdf *.ps *.d *.dmp *.idx 
	-od DIR
		output directory for *.ps *.pdf files. 
		Default is the current directory

	---------------
	Latex-specific (yet to be implemented)
	---------------

	-f 	full latex cycle (set by default)
	-s	single latex + pdf generation
	-c	convert dvi to pdf
	-g	run "makeglossaries" command only

USAGE EXAMPLES:
	ltm rep 
		( source file rep.tex, output rep.pdf )
SCRIPT LOCATION:
	$0
=============================================================
EOF
# }}}
	else 
	  # {{{
while [ ! -z "$1" ]
	do
	  case "$1" in
	    "vm") vim $vim_opts $0 ;;
	    "c") rm -f *.ps *.dvi *.bbl *.aux *.bak .*swp *.blg *.log *.lof *~ *.lot *.out *.toc *.backup *.d *.dmp *.idx 
		;;
	    "-f") export  mode="full" ;;
	    "-s") export  mode="simple" ;;
	    "-c") export  mode="convert" ;;
	    "-g") export  mode="gls" ;;
	    "-od") export outdir=$2; shift ;;
	    *) 
	    		export fname=${1%.tex} 
				export ffile=$fname.pdf
	    	if [ -f $1.tex ]; then 
	      		dojob $mode 
		      else
			echo "No such file! Exiting..."
			exit 1
		fi
		;;
	  esac
	  shift
	  # }}}
done

fi

