#!/bin/bash

# {{{
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `

vim_opts="-n -p"
v="vim $vim_opts"
rsync="rsync -avz --size-only"

alias cdop="cd ~/svn/SCRIPTS/op/"

sync_files=( ".vimrc" ".bashrc" ".pinerc"  ) 
sync_dirs=( "scripts" "vrt" "templates" "doc/coms" ) 

sbdirs(){
# main Wales group software directory

export wg_dir="$shd/../../"
packdir=$HOME/arch/packed
unpackdir=$HOME/arch/unpacked

}
# }}}

dhelp(){
# general {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: ~/scripts
PURPOSE: synchronizing 
USAGE: $this_script [ OPTIONS ] 

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	
	============
EOF
# }}}
# script-specific {{{
cat << EOF

	Specific

	---------------
	Wales group
	---------------

	op 		in SCRIPTS/: sync:
       				op and all with clust 

	iwg		scp iwg => venus

	clust vn www mq

	---------------

	cit 		synchronize between the main citation directory 
				doc/cit 
			and other directories containing bib-files
	
	---------------
	
 	${sync_files[@]}

REMARKS:
AUTHOR: O. Poplavskyy
EXAMPLES:
	$this_script srcf 
		copy ${sync_files[@]} to 
			$srcf
	$this_script srcf .bashrc 
		copy only .bashrc to 
			$srcf
=============================================
EOF
# }}}
}

[ -z $* ] && ( dhelp; exit 0 )

# main part 
# {{{

script_opts=( $* )

while [ ! -z "$1" ]; do
  	arg="$1"
  	shift
  	case "$arg" in
		  # {{{
	  	vm) $v $0; exit ;;
		h) dhelp $*; exit ;;
		iwg) cd ~/svn/SCRIPTS/op/; $rsync iwg $venus:~/ ;;
		op) cd ~/svn/SCRIPTS/
			$rsync ./op ./all $clust:~/svn/SCRIPTS/ 
		;;
		rep) 
		$rsync $HOME/wrk/rep/ $venus:~/rep/
		;;
		srcf | clust | mq | vn | www) 
		# {{{
			case $arg in
			  	clust) host=clust ;;
			  	mq) host=mek-quake ;;
			  	vn) host=0502790@venus.phys.uu.nl ;;
			  	www) host=op226@www-wales.ch.private.cam.ac.uk ;;
			  	srcf) host=op226@shell.srcf.ucam.org ;;
			esac
			cd $HOME
			dest=$host:~/
			case "$1" in
			  	"") for file in ${sync_files[@]}; do
					#$rsync $file $dest
						echo $file
						scp -r $file $dest
					done 
				   ;;
				*) $rsync $1 $dest ;;
		        esac
			;;
			# }}}
		iwg) rsync iwg $venus:~/ ;;
	  	*) ;;
	esac
        #}}}
done

# }}}
