#!/bin/bash
 
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `
# main Wales group software directory
export wg_dir="$shd/../../"

hm=$HOME
unpackdir=$hm/arch/unpacked/

vim_opts="-n -p"
v="vim $vim_opts"

display_help(){
# {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PURPOSE: 
USAGE: $this_script [ OPTIONS ] 

	OPTIONS:

	============
	General
	============
			display the help message
	vm		v(iew) m(yself), i.e., edit this script
	
	============

	pine
	ab		~/.addressbook

REMARKS:
=============================================
EOF
# }}}
}

[ -z $* ] && display_help

# main part 
# {{{

script_opts=( $* )

while [ ! -z "$1" ]; do
  	case "$1" in
	  	vm) $v $0; exit ;;
		pine) $v $unpackdir/alpine-2.00/alpine/alpine.c ;;
		ab) $v $hm/.addressbook $hm/laptop.vcf ;;
	  	*) ;;
	esac
	shift
done

# }}}

