#!/bin/bash

# sbvars()  dhelp() {{{

eo(){
echo "$this_script> $*"
}

sbvars(){
# {{{
s_purpose="view source files with vim"
s_project="~/scripts"

# name of this script 
export this_script=` basename $0 `
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"

vim_opts="-n -p"
v="vim $vim_opts"
repos=( "config" "scripts" "templates" "vrt" "install" "doc-coms" "doc-cit" )

entryserver="citadel.ch.cam.ac.uk"
username="op226"
machine="mek-quake"
port=10000

# }}}
}

sbvars

dhelp(){
#{{{
cat << EOF
SCRIPT NAME: 	$this_script
PURPOSE: 	 	open an ssh tunnel through an external server 
USAGE: 		$this_script -d -p PORT -m  MACHINE -s SERVER
				WHERE:
					-d 	execute with default values (see below)
					-p 	specify port
					-m 	specify machine
					-s 	specify entry server

DEFAULT VALUES:	
			PORT=$port
			MACHINE=$machine
			SERVER=$entryserver

SCRIPT LOCATION:
	$0
EOF
#}}}
}

[ -z "$*" ] && ( dhelp; exit 0 )

#}}}

main(){
# {{{

while [ ! -z "$1" ] 
	do 
		case "$1" in
			"-p") 	 port="$2" ;; 
			"-m")	 machine="$2" ;; 
			"-s") 	 entryserver="$2" ;;
			"-d") 	
				eo " Setting up an ssh tunnel on port $port, machine $machine..."
				ssh -N -f -L $port:$machine.ch.cam.ac.uk:22 -l $username $entryserver
				#break
			;;
		esac
		shift
done
}

# }}}

# main part 
# {{{

script_opts=( $* )

while [ ! -z "$1" ]; do
	  case "$1" in
		  #{{{
		  vm) $v $0 $hm/scripts/f.sh; exit ;;
		h) dhelp $*; exit ;;
		-g) v="$v -g" ;;
		  *) main $* && exit 0 ;;
	esac
	  shift
		#}}}
done
# }}}
