#!/bin/bash

entryserver="citadel.ch.cam.ac.uk"
username="op226"
machine="mek-quake"
port=10000

if [ -z "$*"  ]
 	then
echo "==================================================================="
echo "SCRIPT NAME: 	tunnel "
echo "PURPOSE: 	 	open an ssh tunnel through an external server "
echo "USAGE: 		tunnel -d -p PORT -m  MACHINE -s SERVER"
echo "				WHERE:"
echo "					-d 	execute with default values (see below)"
echo "					-p 	specify port"
echo "					-m 	specify machine"
echo "					-s 	specify entry server"
echo "DEFAULT VALUES:	"
echo "			PORT=$port"
echo "			MACHINE=$machine"
echo "			SERVER=$entryserver"
echo "==================================================================="
	else 
    		while [ ! -z "$1" ] 
    			do 
	 			case "$1" in
		 			"-p") 	 port="$2" ;; 
					"-m")	 machine="$2" ;; 
					"-s") 	 entryserver="$2" ;;
					"-d") 	
    			echo "tunnel> Setting up an ssh tunnel on port $port, machine $machine..."
    			ssh -N -f -L $port:$machine.ch.cam.ac.uk:22 -l $username $entryserver
						 #break
					 	 ;;
				esac
				shift
		done
fi


