#!/bin/bash
# sub:vdoc - view/browse different documents {{{

export pdfv="apvlv"
export tv="vim"

viewers=( apvlv evince foxit gv acroread )

until [ -z "$1" ]
	do 

case "$1" in
	# define the appropriate viewer {{{
	"[0-9]") pdfv="${viewers[$1]}"  ;;
	# }}}
    	"vi") $brw $webdir/vimdoc/vimdoc.sourceforge.net/htmldoc/index.html ;;
# gfortran
	"gf") $brw $HOME/websites/gf/gcc.gnu.org/onlinedocs/gcc-4.5.0/gfortran/index.html ;;
# APACHE 
	"ap") $brw $unpackdir/apache-docs/index.html ;;
# mutt
	"mutt") $tv $hm/share/doc/mutt/manual.txt ;;
# AFNL FORTRAN LIBRARY
	"afnl") $pdfv $wcdir/doc/afnl/lib.pdf & ;;
# LAPACK 95 - FORTRAN 95 interface to the LAPACK library
	"l95") $brw $webdir/l95/www.netlib.org/lapack96/lug95/index.html ;;
# vim tips wiki
	"vv")  $brw  $webdir/vv/vim.wikia.com/wiki/Vim_Tips_Wiki.html ;;
	"vb") $pdfv $hm/books/vimbook.pdf ;;
# LAPACK 3 library 
	"lug") $brw $webdir/lug/www.netlib.org/lapack/lug/index.html ;;
# WCHF user guide
	"wchf") $pdfv $wcdir/doc/wchf.pdf ;;
# DISLIN plotting library
	"dislin") $brw /home/apopl/websites/dislin/www.mps.mpg.de/dislin/contents.html ;;
# Anis - java applet for gif animations
	"anis") $brw $unpackdir/anis/anisdoc.html ;;
# Wales Group {{{
# Energy Landscapes by D. J. Wales
	"el") $pdfv $hm/doc/el.pdf ;;
# OPTIM
	"optim") $pdfv $svndir/DOC/OPTIM.pdf ;;
# GMIN
	"gmin") $pdfv $svndir/DOC/GMIN.pdf ;;
# }}}
# gnuplotfortran
	"gpf")	$pdfv $wcdir/doc/gnuplotfortran.pdf;;
# intel debugger
	"idb1") $brw $ifortdir/Documentation/en_US/idb/Getting_Started.html  ;;
	"idb2") $pdfv $ifortdir/Documentation/en_US/idb/IDB_command_reference.pdf ;;
# awk
	"awk") ;;
  esac

done
