#!/usr/bin/env bash

# sbvars() dhelp() {{{

sbvars(){
# {{{
s_purpose=" Remove papers "
s_project=" ~/scripts"

# name of this script 
export this_script=` basename $0 `
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# shell functions file
export fsh="$hm/scripts/f.sh"
export pdfview="evince"

export field="ChemPhys"
export pdir="$hm/doc/papers/$field/"

vim_opts="-n -p"
v="vim $vim_opts"
gitdirs=( "config" "scripts" "templates" "vrt" "install" "coms" "cit" )

# }}}
}

sbvars
source $fsh

dhelp(){
# {{{
# general beginning part {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: $s_project
PURPOSE: $s_purpose
USAGE: $this_script [ OPTIONS ] 

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	-g		gvim invocation
	
	============
EOF
# }}}
# actual interesting part {{{
cat << EOF

DEFAULTS:

	Field:
		$field
	Papers directory:
		$pdir

EOF
# }}}
# final general part {{{
cat << EOF
REMARKS:
AUTHOR: O. Poplavskyy
SCRIPT LOCATION:
	$0
=============================================
EOF
# }}}
# }}}
}

[ -z "$*" ] && ( dhelp; exit 0 )

#}}}

main(){

# intro messages {{{

e_delim 100 "="
eoos "Input (PDF) papers directory: $papdir" 
eoos "Output (DJVU) directory: $ddir" 

#}}}
# while-loop  {{{

while [ ! -z "$1" ]; do 
	case "$1" in
	  "") ;;
	  -s) # short paper key {{{
	  	eoos "-s: short paper key option"	
	  	export pkey=`lpk $2 ` ; 
		 	eoos "Short paper key provided: $2"  
		if [ ! -z $pkey ]; then 
		 	eoos "Long paper key is: $pkey"  
		  else
		 	eoor "Couldn't convert to the long form: $2"  
		  fi
	  shift ;;
		# }}}
	  *) pkey=$1  
		 	eoos "Long paper key is: $pkey"  
			;;
	esac    
	shift
done

#}}}
# dealing with files {{{

if [ ! -z $pkey ]; then  
	files=( ` find $papdir -name $pkey\*.pdf ` )
		  for p in ${files[@]}; do
				$pdfview $p
		  done
fi
#}}}

}

# main part 
# {{{

script_opts=( $* )

# read cmd args => main()  {{{
while [ ! -z "$1" ]; do
  	case "$1" in
		  #{{{
	  	vm) $v $0 $hm/scripts/f.sh; exit ;;
		h) dhelp $*; exit ;;
		-g) v="$v -g" ;;
	  	*) main $* && exit 0 ;;
	esac
  	shift
        #}}}
done

# }}}
