#!/bin/bash

this_script_dir="`dirname $(readlink -f $0)`"
this_script=` basename $0 `
source "$this_script_dir/sh/func.sh"

case "$HOSTNAME" in
  	"op-laptop") tv=vim ;;
  	*) tv=$HOME/bin/vim ;;
esac

vim_args="$@"
opt=""
    
# }}}

if [ -z "$1" ]
	then
		echo_h "$this_script"
	else # read command-line arguments {{{
until [ ! -z "$1" ]
	do 
		case "$1" in
			"-o") vim_opts="$2 | $vim_opts" ;;
			"-c") vim_coms="$2 | $vim_coms" ;;
			"-f") vim_coms="set ft=$2 | $vim_coms"  ;;
			"-g") tv=gvim ;;
			*) vim_args="$@" ;;
		esac
		shift
done

$tv $vim_opts +"$vim_coms"  "$vim_args"

fi # }}}
