#!/usr/bin/env bash
 
# directory where this script resides
export shd="`dirname $(readlink -f $0)`"
# name of this script 
export this_script=` basename $0 `

vim_opts="-n -p"
#vim_opts="$vim_opts -g" 
v="vim $vim_opts"
repos=( "config" "scripts" "templates" "vrt" "install" "doc-coms" "doc-cit" )

define_base_dirs(){
# {{{
# main Wales group software directory
export wg_dir="$shd/../../"
packdir=$HOME/arch/packed
unpackdir=$HOME/arch/unpacked
# }}}
}


set_base_vars(){
# {{{
s_purpose="view paper's tex source"
s_project="~/scripts"
# }}}
}

set_base_vars

display_help(){
# {{{
# general beginning part {{{
cat << EOF
=============================================
SCRIPT NAME: $this_script 
PROJECT: $s_project
PURPOSE: $s_purpose
USAGE: $this_script [ OPTIONS ] 

	OPTIONS:

	============
	General
	============

			display the help message

	vm		v(iew) m(yself), i.e., edit this script
	-g		gvim invocation
	
	============
EOF
# }}}
# actual interesting part {{{
cat << EOF

pf		Protein folding
pull		Pulling experiments and theory
bln		BLN model

pf:
	1 	Thirumalai10	

pull:
	1	ToanThirumalai10

bln:
	1	GuoBrooks97	

EOF
# }}}
# final general part {{{
cat << EOF
REMARKS:
AUTHOR: O. Poplavskyy
=============================================
EOF
# }}}
# }}}
}

[ -z "$*" ] && ( display_help; exit 0 )

main(){
# {{{

ptexdir="$hm/wrk/p/"

case "$1" in
  pull) # {{{
	paps=( ToanThirumalai10 ) 
  ;;
	#}}}
	*) files=( ` find $ptexdir -name p.$1\*.\*.tex -o -name p.$1\*.tex ` \
				pap-nc.0.tex pap-preamble.0.tex \ 
				`find $ptexdir -name up.$1\*.i.dat `) ;;
esac    

#files=( ` ls p.${paps[$2]}.*.tex ` )
$v ${files[@]}

# }}}
}

# main part 
# {{{

script_opts=( $* )
define_base_dirs

while [ ! -z "$1" ]; do
  	case "$1" in
		  #{{{
	  	vm) $v $0; exit ;;
		h) display_help $*; exit ;;
		-g) v="$v -g" ;;
	  	*) main $* && exit 0 ;;
	esac
  	shift
        #}}}
done

# }}}


